/** Foto locali in /public/images — niente hotlink Unsplash che si rompe. */
export const IMAGES = {
  hero: '/images/hero.jpg',
  street: '/images/driving.jpg',
  city: '/images/city-night.jpg',
  night: '/images/night-car.jpg',
  traffic: '/images/parking-signs.jpg',
  parkingLot: '/images/parking-lot.jpg',
  rainStreet: '/images/rain-city.jpg',
  evening: '/images/night-car.jpg',
  phoneNav: '/images/phone.jpg',
  friends: '/images/friends.jpg',
  laptop: '/images/laptop.jpg',
  keys: '/images/keys.jpg',
  mapHands: '/images/map.jpg',
  morning: '/images/keys.jpg',
  italyStreet: '/images/europe-street.jpg',
  carsRow: '/images/cars-row.jpg',
  crosswalk: '/images/train.jpg',
  skyline: '/images/city-night.jpg',
  streetParked: '/images/street-parked.jpg',
  carStreet: '/images/car-street.jpg',
  blueCar: '/images/blue-car.jpg',
  train: '/images/train.jpg',
} as const;
